apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-webapp
  template:
    metadata:
      labels:
        app: todo-webapp
    spec:
      containers:
      - name: todo-container
        image: houbou98/todoapp:latest
        ports:
        - containerPort: 80
        envFrom: 
        - configMapRef:
            name: app-config